"""Executable reference runner for the Website Generation & Deployment Factory.

The architecture lives in docs/website-factory/. This package is the smallest
honest implementation of it: six nodes, one canonical envelope per edge, a
quality gate in front of every hand-off, and a deterministic static site build
at the end.

Deliberate constraints:
  * No network calls and no API keys, so a run is reproducible in CI and the
    published site can be regenerated byte-for-byte from source.
  * The creative nodes (ideation, product definition, design) are pinned to the
    decisions already recorded in docs/fieldflow-spec.md. Swapping any of them
    for a real model call touches one function, never a neighbour, because the
    schema is the contract.
  * Secrets are referenced by name only. No credential value enters a payload,
    an artifact, a log line, or a URL.

Entry point:
    python -m website_factory.run --out dist
"""

from website_factory.envelope import (
    ENVELOPE_VERSION,
    ContractError,
    Envelope,
    GateFailure,
    Quality,
)

__version__ = "1.0.0"

__all__ = [
    "ENVELOPE_VERSION",
    "ContractError",
    "Envelope",
    "GateFailure",
    "Quality",
    "__version__",
]
