"""Node 4 (software engineer): design.system + product.spec -> code.bundle.

Boring, readable output on purpose. The bundle is hand-written HTML and CSS with
no build step, no framework and no JavaScript, because the job of this page is
to load instantly on a phone in a driveway and to survive being hosted on a
static file server for years.

What this node refuses to do:

  * pick a colour, a size or a spacing value - every one of those comes from the
    design tokens, so a design change is a token change;
  * write copy - every string comes from the product spec;
  * emit a secret - scan_for_secrets() runs over the generated bytes and is a
    hard violation, which is the deterministic stand-in for gitleaks in G4.

The bundle is returned as an in-memory mapping of relative path to text. It
touches no disk, so the renderer is trivially testable and the deployment node
stays the only thing in the pipeline that writes files.
"""

from __future__ import annotations

import html
from typing import Any, Dict, List

from website_factory.envelope import Quality, require

G4_THRESHOLD = 0.85
G4_WEIGHTS = {
    "modularity": 0.3,
    "readability": 0.2,
    "spec_coverage": 0.3,
    "a11y_markup": 0.2,
}

BUNDLE_CONTRACT = ("files", "entrypoints", "routes")
GENERATOR = "website_factory"

REQUIRED_FILES = (
    "index.html",
    "styles.css",
    "404.html",
    "robots.txt",
    "sitemap.xml",
    ".nojekyll",
)

# Deterministic secret scan. Credential values must never reach a commit, a log
# or a URL, so the check runs on the generated bytes rather than on trust.
SECRET_MARKERS = (
    ("openai style key", "sk-"),
    ("aws access key id", "AKIA"),
    ("pem private key", "BEGIN PRIVATE KEY"),
    ("rsa private key", "BEGIN RSA PRIVATE KEY"),
    ("github token", "ghp_"),
    ("slack token", "xoxb-"),
    ("twilio auth token assignment", "TWILIO_AUTH_TOKEN="),
    ("service role key assignment", "SERVICE_ROLE_KEY="),
)

STATIC_CSS = """
*, *::before, *::after { box-sizing: border-box; }

html { -webkit-text-size-adjust: 100%; }

body {
  margin: 0;
  background: var(--color-surface);
  color: var(--color-ink);
  font-family: var(--font-sans);
  font-size: var(--font-scale-body);
  line-height: var(--font-leading-body);
}

.wrap {
  width: 100%;
  max-width: var(--shape-wrap);
  margin: 0 auto;
  padding: 0 var(--space-4);
}

.skip {
  position: absolute;
  left: -9999px;
}

.skip:focus {
  left: var(--space-4);
  top: var(--space-4);
  z-index: 10;
  background: var(--color-surface);
  color: var(--color-ink);
  padding: var(--space-2) var(--space-3);
  border: var(--shape-border) solid var(--color-line);
  border-radius: var(--shape-radius);
}

a { color: var(--color-brand); }

a:focus-visible, .btn:focus-visible {
  outline: 3px solid var(--color-brand);
  outline-offset: 2px;
}

header.topbar {
  border-bottom: var(--shape-border) solid var(--color-line);
  background: var(--color-surface);
}

.topbar-inner {
  display: flex;
  flex-wrap: wrap;
  align-items: center;
  gap: var(--space-4);
  padding-top: var(--space-4);
  padding-bottom: var(--space-4);
}

.brand {
  font-weight: 700;
  font-size: 1.25rem;
  text-decoration: none;
  color: var(--color-ink);
}

.brand span { color: var(--color-brand); }

nav.nav {
  display: flex;
  flex-wrap: wrap;
  gap: var(--space-4);
  margin-left: auto;
  font-size: var(--font-scale-small);
}

h1, h2, h3 { line-height: var(--font-leading-tight); }

h1 {
  font-size: var(--font-scale-hero);
  margin: 0 0 var(--space-4);
  max-width: 34ch;
}

h2 {
  font-size: var(--font-scale-h2);
  margin: 0 0 var(--space-4);
}

h3 { font-size: 1.0625rem; margin: 0 0 var(--space-2); }

p { max-width: var(--shape-measure); }

.hero { padding: var(--space-16) 0 var(--space-12); }

.lede { font-size: 1.1875rem; }

.muted { color: var(--color-ink-muted); }

.small { font-size: var(--font-scale-small); color: var(--color-ink-muted); }

.status {
  border-left: 3px solid var(--color-brand);
  padding: var(--space-2) var(--space-4);
  background: var(--color-surface-alt);
  border-radius: 0 var(--shape-radius) var(--shape-radius) 0;
}

.row {
  display: flex;
  flex-wrap: wrap;
  gap: var(--space-3);
  align-items: center;
}

.btn {
  display: inline-block;
  background: var(--color-brand);
  color: var(--color-brand-ink);
  text-decoration: none;
  font-weight: 600;
  padding: var(--space-3) var(--space-6);
  border-radius: var(--shape-radius-pill);
}

.btn-quiet {
  background: transparent;
  color: var(--color-brand);
  border: var(--shape-border) solid var(--color-line);
}

section.band { padding: var(--space-12) 0; }

section.band + section.band { border-top: var(--shape-border) solid var(--color-line); }

.grid {
  display: grid;
  gap: var(--space-4);
  grid-template-columns: 1fr;
}

@media (min-width: 38rem) {
  .grid { grid-template-columns: repeat(2, 1fr); }
}

.card {
  background: var(--color-surface-alt);
  border: var(--shape-border) solid var(--color-line);
  border-radius: var(--shape-radius);
  padding: var(--space-6);
}

.card p { max-width: none; }

ol.steps { padding-left: var(--space-6); }

ol.steps li { margin-bottom: var(--space-4); }

.phase {
  border-left: 3px solid var(--color-line);
  padding-left: var(--space-4);
  margin-bottom: var(--space-6);
}

.phase ul { margin: var(--space-2) 0 0; padding-left: var(--space-6); }

dl.faq dt { font-weight: 600; margin-top: var(--space-4); }

dl.faq dd { margin: var(--space-2) 0 0; color: var(--color-ink-muted); }

ul.links { list-style: none; padding: 0; display: grid; gap: var(--space-2); }

footer.site {
  background: var(--color-footer);
  color: var(--color-footer-ink);
  padding: var(--space-8) 0;
  font-size: var(--font-scale-small);
}

footer.site a { color: var(--color-footer-ink); }

footer.site p { max-width: none; margin: 0 0 var(--space-2); }
"""


def esc(value: Any) -> str:
    return html.escape(str(value), quote=True)


def build_css(tokens: Dict[str, Dict[str, str]]) -> str:
    """Design tokens become CSS custom properties, one to one."""
    lines = ["/* Generated from design.system tokens. Do not hand-edit. */", ":root {"]
    for group in ("color", "font", "space", "shape"):
        for name, value in tokens[group].items():
            lines.append("  --%s-%s: %s;" % (group, name, value))
    lines.append("}")
    return "\n".join(lines) + STATIC_CSS


def _brand_markup(name: str) -> str:
    """Split a CamelCase product name so the second half can take brand colour."""
    for index in range(1, len(name)):
        if name[index].isupper():
            return "%s<span>%s</span>" % (esc(name[:index]), esc(name[index:]))
    return esc(name)


def _head(title: str, description: str, canonical: str, version: str) -> List[str]:
    return [
        "<!doctype html>",
        '<html lang="en">',
        "<head>",
        '<meta charset="utf-8">',
        '<meta name="viewport" content="width=device-width, initial-scale=1">',
        "<title>%s</title>" % esc(title),
        '<meta name="description" content="%s">' % esc(description),
        '<meta name="generator" content="%s %s">' % (esc(GENERATOR), esc(version)),
        '<link rel="canonical" href="%s">' % esc(canonical),
        '<link rel="stylesheet" href="styles.css">',
        "</head>",
    ]


NAV = (
    ("What it does", "#what"),
    ("How it works", "#how-it-works"),
    ("Build order", "#build-order"),
    ("Straight answers", "#faq"),
)


def _topbar(spec: Dict[str, Any], with_nav: bool) -> List[str]:
    out = [
        '<a class="skip" href="#main">Skip to content</a>',
        '<header class="topbar">',
        '<div class="wrap topbar-inner">',
        '<a class="brand" href="./">%s</a>' % _brand_markup(spec["product_name"]),
    ]
    if with_nav:
        out.append('<nav class="nav" aria-label="Sections">')
        for label, href in NAV:
            out.append('<a href="%s">%s</a>' % (esc(href), esc(label)))
        out.append("</nav>")
    out.extend(["</div>", "</header>"])
    return out


def _footer(spec: Dict[str, Any]) -> List[str]:
    return [
        '<footer class="site">',
        '<div class="wrap">',
        "<p>%s, part of %s.</p>"
        % (esc(spec["product_name"]), esc(spec["parent_brand"])),
        "<p>%s</p>" % esc(spec["positioning"]),
        "<p>This page was generated from the product spec by the website "
        "factory in this repository.</p>",
        "</div>",
        "</footer>",
        "</body>",
        "</html>",
    ]


def index_html(
    spec: Dict[str, Any],
    design: Dict[str, Any],
    canonical: str,
    version: str = "1.0.0",
) -> str:
    sections = spec["sections"]
    hero = sections["hero"]
    headline = spec["positioning"].split(",")[0]
    title = "%s - %s" % (spec["product_name"], headline)

    out = _head(title, hero["lede"], canonical, version)
    out.append("<body>")
    out.extend(_topbar(spec, with_nav=True))
    out.append('<main id="main">')

    # Hero
    out.extend(
        [
            '<section class="hero">',
            '<div class="wrap">',
            "<h1>%s</h1>" % esc(hero["heading"]),
            '<p class="lede">%s</p>' % esc(hero["lede"]),
            '<p class="muted">%s</p>' % esc(hero["problem"]),
            '<p class="row">',
            '<a class="btn" href="%s">%s</a>'
            % (esc(hero["primary_cta"]["href"]), esc(hero["primary_cta"]["label"])),
            '<a class="btn btn-quiet" href="%s">%s</a>'
            % (
                esc(hero["secondary_cta"]["href"]),
                esc(hero["secondary_cta"]["label"]),
            ),
            "</p>",
            '<p class="small">%s</p>' % esc(hero["note"]),
            '<p class="status small">%s</p>' % esc(spec["status_note"]),
            "</div>",
            "</section>",
        ]
    )

    # Features
    features = sections["features"]
    out.extend(
        [
            '<section class="band" id="what">',
            '<div class="wrap">',
            "<h2>%s</h2>" % esc(features["heading"]),
            '<div class="grid">',
        ]
    )
    for item in features["items"]:
        out.extend(
            [
                '<article class="card">',
                "<h3>%s</h3>" % esc(item["title"]),
                "<p>%s</p>" % esc(item["body"]),
                '<p class="small">%s</p>' % esc(item["evidence"]),
                "</article>",
            ]
        )
    out.extend(["</div>", "</div>", "</section>"])

    # How it works
    how = sections["how_it_works"]
    out.extend(
        [
            '<section class="band" id="how-it-works">',
            '<div class="wrap">',
            "<h2>%s</h2>" % esc(how["heading"]),
            '<ol class="steps">',
        ]
    )
    for step in how["steps"]:
        out.append(
            "<li><strong>%s.</strong> %s</li>"
            % (esc(step["title"]), esc(step["body"]))
        )
    out.extend(["</ol>", "</div>", "</section>"])

    # Roadmap plus the published exclusion list
    road = sections["roadmap"]
    out.extend(
        [
            '<section class="band" id="build-order">',
            '<div class="wrap">',
            "<h2>%s</h2>" % esc(road["heading"]),
            '<p class="muted">%s</p>' % esc(road["note"]),
        ]
    )
    for phase in spec["roadmap"]:
        out.extend(
            [
                '<div class="phase">',
                "<h3>Phase %s - %s</h3>" % (esc(phase["phase"]), esc(phase["name"])),
                '<p class="muted">%s</p>' % esc(phase["outcome"]),
                "<ul>",
            ]
        )
        for entry in phase["items"]:
            out.append("<li>%s</li>" % esc(entry))
        out.extend(["</ul>", "</div>"])
    out.extend(["<h3>Not being built yet</h3>", "<ul>"])
    for excluded in spec["out_of_scope"]:
        out.append("<li>%s</li>" % esc(excluded))
    out.extend(["</ul>", "</div>", "</section>"])

    # FAQ
    faq = sections["faq"]
    out.extend(
        [
            '<section class="band" id="faq">',
            '<div class="wrap">',
            "<h2>%s</h2>" % esc(faq["heading"]),
            '<dl class="faq">',
        ]
    )
    for entry in faq["items"]:
        out.append("<dt>%s</dt>" % esc(entry["question"]))
        out.append("<dd>%s</dd>" % esc(entry["answer"]))
    out.extend(["</dl>", "</div>", "</section>"])

    # Closing
    closing = sections["closing"]
    out.extend(
        [
            '<section class="band" id="where">',
            '<div class="wrap">',
            "<h2>%s</h2>" % esc(closing["heading"]),
            "<p>%s</p>" % esc(closing["body"]),
            '<ul class="links">',
        ]
    )
    for link in closing["links"]:
        out.append(
            '<li><a href="%s">%s</a></li>'
            % (esc(link["href"]), esc(link["label"]))
        )
    out.extend(["</ul>", "</div>", "</section>", "</main>"])
    out.extend(_footer(spec))
    return "\n".join(out) + "\n"


def not_found_html(
    spec: Dict[str, Any], canonical: str, version: str = "1.0.0"
) -> str:
    title = "Page not found - %s" % spec["product_name"]
    out = _head(title, "That page does not exist.", canonical, version)
    out.append("<body>")
    out.extend(_topbar(spec, with_nav=False))
    out.extend(
        [
            '<main id="main">',
            '<section class="hero">',
            '<div class="wrap">',
            "<h1>That page does not exist.</h1>",
            '<p class="lede">The link may be old, or it may be a page that was '
            "never built. Both happen.</p>",
            '<p class="row"><a class="btn" href="./">Back to the start</a></p>',
            "</div>",
            "</section>",
            "</main>",
        ]
    )
    out.extend(_footer(spec))
    return "\n".join(out) + "\n"


def robots_txt(base_url: str) -> str:
    lines = [
        "User-agent: *",
        "Allow: /",
        "",
        "Sitemap: %ssitemap.xml" % base_url,
    ]
    return "\n".join(lines) + "\n"


def sitemap_xml(base_url: str) -> str:
    lines = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">',
        "  <url>",
        "    <loc>%s</loc>" % esc(base_url),
        "    <changefreq>monthly</changefreq>",
        "  </url>",
        "</urlset>",
    ]
    return "\n".join(lines) + "\n"


def render_bundle(
    spec: Dict[str, Any],
    design: Dict[str, Any],
    base_url: str = "/",
    version: str = "1.0.0",
) -> Dict[str, Any]:
    """design.system + product.spec -> code.bundle (in memory, never on disk)."""
    require(spec, ("product_name", "positioning", "sections", "roadmap"), "software_engineer")
    require(design, ("tokens",), "software_engineer")

    base = base_url if base_url.endswith("/") else base_url + "/"
    files = {
        "index.html": index_html(spec, design, base, version),
        "styles.css": build_css(design["tokens"]),
        "404.html": not_found_html(spec, base + "404.html", version),
        "robots.txt": robots_txt(base),
        "sitemap.xml": sitemap_xml(base),
        # Tells GitHub Pages to serve the files as they are, with no Jekyll pass.
        ".nojekyll": "",
    }
    return {
        "files": files,
        "entrypoints": {"document": "index.html", "stylesheet": "styles.css"},
        "routes": ["/", "/404.html"],
        "base_url": base,
        "generator": GENERATOR,
        "version": version,
        "toolchain": {
            "install": "none - standard library only",
            "build": "python -m website_factory.run",
            "test": "pytest -q",
        },
    }


def scan_for_secrets(files: Dict[str, str]) -> List[str]:
    """Deterministic stand-in for gitleaks. No credential value ships, ever."""
    found = []
    for path, text in sorted(files.items()):
        for label, marker in SECRET_MARKERS:
            if marker in text:
                found.append("%s looks like it contains a %s" % (path, label))
    return found


def _a11y_checks(document: str) -> Dict[str, bool]:
    return {
        "lang attribute": 'lang="en"' in document,
        "skip link": 'class="skip"' in document,
        "exactly one h1": document.count("<h1") == 1,
        "header landmark": "<header" in document,
        "main landmark": '<main id="main"' in document,
        "footer landmark": "<footer" in document,
        "every image has alt text": document.count("<img")
        == document.count("alt="),
        "page has a title": "<title>" in document,
    }


def grade_bundle(bundle: Dict[str, Any], spec: Dict[str, Any]) -> Quality:
    """Gate G4: files present, no secrets, accessible markup, spec covered."""
    require(bundle, BUNDLE_CONTRACT, "software_engineer")
    files: Dict[str, str] = bundle["files"]
    violations: List[str] = []

    for name in REQUIRED_FILES:
        if name not in files:
            violations.append("bundle is missing %s" % name)
    violations.extend(scan_for_secrets(files))

    document = files.get("index.html", "")
    checks = _a11y_checks(document)
    for label, passed in sorted(checks.items()):
        if not passed:
            violations.append("accessibility check failed: %s" % label)

    expected = [item["title"] for item in spec["sections"]["features"]["items"]]
    expected += [entry["question"] for entry in spec["sections"]["faq"]["items"]]
    expected += list(spec["out_of_scope"])
    missing = [text for text in expected if esc(text) not in document]
    for text in missing:
        violations.append("the site does not render %r" % text)

    long_lines = 0
    total_lines = 0
    for name in ("index.html", "styles.css", "404.html"):
        for line in files.get(name, "").splitlines():
            total_lines += 1
            if len(line) > 120:
                long_lines += 1

    rubric = {
        # proxy: the bundle ships every file the host needs
        "modularity": min(1.0, len(files) / float(len(REQUIRED_FILES))),
        # proxy: no unreadably long generated lines
        "readability": 1.0
        if total_lines == 0
        else round((total_lines - long_lines) / float(total_lines), 4),
        # proxy: every promise in the spec appears in the markup
        "spec_coverage": 1.0
        if not expected
        else round((len(expected) - len(missing)) / float(len(expected)), 4),
        # proxy: accessibility checks that passed
        "a11y_markup": round(
            len([ok for ok in checks.values() if ok]) / float(len(checks)), 4
        ),
    }
    return Quality(
        threshold=G4_THRESHOLD,
        rubric=rubric,
        weights=G4_WEIGHTS,
        violations=violations,
    )
